name: untitled
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <=3.3.1'

dependencies:
   http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  email_validator: